[workspace]
members = [
    "ble",
    # "nrf5x-hci", FIXME: disabling as rust testing won't work with pac
]

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1 # better optimizations
opt-level = "s"
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations